import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { test, expect } from "./fixtures";
import type { Page } from "@playwright/test";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_BODY = readFileSync(
  join(__dirname, "fixtures/markdown-footnotes/sample.md"),
  "utf8",
);

const FIXTURES_DIR = "/e2e/fixtures";
const FILE = `${FIXTURES_DIR}/footnotes.md`;

async function setupMocks(page: Page): Promise<void> {
  await page.addInitScript(
    ({ dir, file, body }: { dir: string; file: string; body: string }) => {
      const w = window as unknown as Record<string, unknown>;
      w.__TAURI_IPC_MOCK__ = async (cmd: string) => {
        if (cmd === "get_launch_args") return { files: [], folders: [dir] };
        if (cmd === "read_dir") return [{ name: "footnotes.md", path: file, is_dir: false }];
        if (cmd === "read_text_file") return body;
        if (cmd === "load_review_comments") return null;
        if (cmd === "save_review_comments") return null;
        if (cmd === "check_path_exists") return "file";
        if (cmd === "get_log_path") return "/mock/log.log";
        if (cmd === "get_file_comments") return [];
        return null;
      };
    },
    { dir: FIXTURES_DIR, file: FILE, body: FIXTURE_BODY },
  );
}

test.describe("MarkdownViewer GFM footnotes (B2)", () => {
  test.beforeEach(async ({ page }) => {
    await setupMocks(page);
    await page.goto("/");
    await page.locator(".folder-tree").getByText("footnotes.md").click();
    await expect(page.locator(".markdown-body")).toBeVisible();
  });

  test("inline refs render as superscript anchors with footnote hrefs", async ({ page }) => {
    const ref1 = page.locator('.markdown-body sup a[href="#user-content-fn-1"]').first();
    const refLong = page
      .locator('.markdown-body sup a[href="#user-content-fn-longname"]')
      .first();

    await expect(ref1).toBeVisible();
    await expect(refLong).toBeVisible();

    // The anchors are children of a <sup>, which is what gives them the
    // superscript baseline shift remark-gfm relies on.
    await expect(ref1.locator("xpath=..")).toHaveJSProperty("tagName", "SUP");
    await expect(refLong.locator("xpath=..")).toHaveJSProperty("tagName", "SUP");
  });

  test("footnote definitions render with stable ids", async ({ page }) => {
    await expect(page.locator(".markdown-body #user-content-fn-1")).toBeAttached();
    await expect(
      page.locator(".markdown-body #user-content-fn-longname"),
    ).toBeAttached();
  });

  test("clicking a ref scrolls the matching footnote into view", async ({ page }) => {
    const ref1 = page.locator('.markdown-body sup a[href="#user-content-fn-1"]').first();
    const fn1 = page.locator(".markdown-body #user-content-fn-1");

    await ref1.click();

    // Browser handles `#…` fragment scroll. Wait for the footnote to enter
    // the viewport, then verify it is in view (top within window height).
    await expect(fn1).toBeInViewport();
  });

  test("back-ref returns the viewport to the original reference", async ({ page }) => {
    const ref1 = page.locator('.markdown-body sup a[href="#user-content-fn-1"]').first();
    await ref1.click();

    // The back-ref link inside the footnote definition points to the original
    // reference (`#user-content-fnref-1`).
    const backRef = page
      .locator('.markdown-body a[href="#user-content-fnref-1"]')
      .first();
    await expect(backRef).toBeVisible();
    await backRef.click();

    await expect(ref1).toBeInViewport();
  });

  test("Footnotes heading is not duplicated in the table of contents", async ({ page }) => {
    // The TOC must not list the auto-injected "Footnotes" h2 — it is
    // generated by remark-gfm at render time and is not part of the source
    // markdown that `extractHeadings` parses.
    const toc = page.locator(".toc");
    if (await toc.count()) {
      await expect(toc.getByRole("link", { name: /^Footnotes$/i })).toHaveCount(0);
    }
  });
});
